export const CONTRACT_FACTORY_TOKEN_PREFIX = 'ETHERS_TOOLS_CONTRACT_FACTORY_';
export const AUTO_CONTRACT_FACTORY_TOKEN_PREFIX =
  'ETHERS_TOOLS_AUTO_CONTRACT_FACTORY_';
export const MUTLICALL_FACTORY_TOKEN_PREFIX = 'ETHERS_TOOLS_CONTRACT_FACTORY_';
